/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\代码\\前端笔记\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0b474b66",
    path: "/file/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b474b66").then(next)
    },
  },
  {
    path: "/file/index.html",
    redirect: "/file/"
  },
  {
    name: "v-3a568956",
    path: "/file/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a568956").then(next)
    },
  },
  {
    name: "v-3b87372c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b87372c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-0e9f7cde",
    path: "/file/algorithmPerformance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e9f7cde").then(next)
    },
  },
  {
    name: "v-37957ab4",
    path: "/file/arrayBasics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37957ab4").then(next)
    },
  },
  {
    name: "v-5dad5fbe",
    path: "/file/array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5dad5fbe").then(next)
    },
  },
  {
    name: "v-4a3ddff0",
    path: "/file/contact.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a3ddff0").then(next)
    },
  },
  {
    name: "v-2e6992f4",
    path: "/file/expandAlgorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e6992f4").then(next)
    },
  },
  {
    name: "v-d8869f44",
    path: "/file/leetcode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d8869f44").then(next)
    },
  },
  {
    name: "v-816d4c84",
    path: "/file/list.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-816d4c84").then(next)
    },
  },
  {
    name: "v-d64c2504",
    path: "/file/memoryManagement.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d64c2504").then(next)
    },
  },
  {
    name: "v-70f3311e",
    path: "/file/listBasics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70f3311e").then(next)
    },
  },
  {
    name: "v-932ac284",
    path: "/file/search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-932ac284").then(next)
    },
  },
  {
    name: "v-192539be",
    path: "/file/sort.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-192539be").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]