/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "算法思维",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/hero.png",
        "heroText": "算法笔记",
        "tagline": "算法小计",
        "actionText": "快速上手 →",
        "actionLink": "/file/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3b87372c",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/file/",
      "relativePath": "file/README.md",
      "key": "v-0b474b66",
      "path": "/file/"
    },
    {
      "title": "15.三数之和",
      "frontmatter": {},
      "regularPath": "/file/doublePointer.html",
      "relativePath": "file/doublePointer.md",
      "key": "v-ca1b43d0",
      "path": "/file/doublePointer.html",
      "headers": [
        {
          "level": 2,
          "title": "算法思想：",
          "slug": "算法思想"
        },
        {
          "level": 2,
          "title": "复杂度分析",
          "slug": "复杂度分析"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/file/about.html",
      "relativePath": "file/about.md",
      "key": "v-3a568956",
      "path": "/file/about.html"
    },
    {
      "title": "二分查找",
      "frontmatter": {},
      "regularPath": "/file/array.html",
      "relativePath": "file/array.md",
      "key": "v-5dad5fbe",
      "path": "/file/array.html",
      "headers": [
        {
          "level": 2,
          "title": "二分查找",
          "slug": "二分查找"
        }
      ]
    },
    {
      "title": "蓄水池抽样算法",
      "frontmatter": {},
      "regularPath": "/file/expandAlgorithm.html",
      "relativePath": "file/expandAlgorithm.md",
      "key": "v-2e6992f4",
      "path": "/file/expandAlgorithm.html",
      "headers": [
        {
          "level": 2,
          "title": "蓄水池抽样算法",
          "slug": "蓄水池抽样算法"
        },
        {
          "level": 2,
          "title": "鸽巢原理",
          "slug": "鸽巢原理"
        },
        {
          "level": 2,
          "title": "单向BFS",
          "slug": "单向bfs"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/file/contact.html",
      "relativePath": "file/contact.md",
      "key": "v-4a3ddff0",
      "path": "/file/contact.html",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ]
    },
    {
      "title": "时间复杂度",
      "frontmatter": {},
      "regularPath": "/file/algorithmPerformance.html",
      "relativePath": "file/algorithmPerformance.md",
      "key": "v-0e9f7cde",
      "path": "/file/algorithmPerformance.html",
      "headers": [
        {
          "level": 2,
          "title": "时间复杂度",
          "slug": "时间复杂度"
        },
        {
          "level": 3,
          "title": "定义",
          "slug": "定义"
        },
        {
          "level": 2,
          "title": "空间复杂度",
          "slug": "空间复杂度"
        }
      ]
    },
    {
      "title": "注意",
      "frontmatter": {},
      "regularPath": "/file/arrayBasics.html",
      "relativePath": "file/arrayBasics.md",
      "key": "v-37957ab4",
      "path": "/file/arrayBasics.html"
    },
    {
      "title": "373.查找和最小的k对数字",
      "frontmatter": {},
      "regularPath": "/file/leetcode.html",
      "relativePath": "file/leetcode.md",
      "key": "v-d8869f44",
      "path": "/file/leetcode.html",
      "headers": [
        {
          "level": 2,
          "title": "373.查找和最小的k对数字",
          "slug": "_373-查找和最小的k对数字"
        },
        {
          "level": 3,
          "title": "算法思想：",
          "slug": "算法思想"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "264.丑数Ⅱ",
          "slug": "_264-丑数ii"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码-2"
        },
        {
          "level": 2,
          "title": "539.最小时间差",
          "slug": "_539-最小时间差"
        },
        {
          "level": 3,
          "title": "算法思想：",
          "slug": "算法思想-2"
        },
        {
          "level": 3,
          "title": "代码：",
          "slug": "代码-3"
        },
        {
          "level": 2,
          "title": "219.存在重复元素Ⅱ",
          "slug": "_219-存在重复元素ii"
        },
        {
          "level": 3,
          "title": "法一：哈希表，map",
          "slug": "法一-哈希表-map"
        },
        {
          "level": 3,
          "title": "法二：滑动窗口",
          "slug": "法二-滑动窗口"
        }
      ]
    },
    {
      "title": "你好",
      "frontmatter": {},
      "regularPath": "/file/list.html",
      "relativePath": "file/list.md",
      "key": "v-816d4c84",
      "path": "/file/list.html",
      "headers": [
        {
          "level": 2,
          "title": "你好",
          "slug": "你好"
        }
      ]
    },
    {
      "title": "内存对齐",
      "frontmatter": {},
      "regularPath": "/file/memoryManagement.html",
      "relativePath": "file/memoryManagement.md",
      "key": "v-d64c2504",
      "path": "/file/memoryManagement.html",
      "headers": [
        {
          "level": 2,
          "title": "内存对齐",
          "slug": "内存对齐"
        },
        {
          "level": 3,
          "title": "原因",
          "slug": "原因"
        }
      ]
    },
    {
      "title": "搜索",
      "frontmatter": {},
      "regularPath": "/file/search.html",
      "relativePath": "file/search.md",
      "key": "v-932ac284",
      "path": "/file/search.html",
      "headers": [
        {
          "level": 2,
          "title": "顺序搜索",
          "slug": "顺序搜索"
        },
        {
          "level": 3,
          "title": "算法思想",
          "slug": "算法思想"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "二分搜索",
          "slug": "二分搜索"
        },
        {
          "level": 3,
          "title": "算法思想",
          "slug": "算法思想-2"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码-2"
        }
      ]
    },
    {
      "title": "排序算法的分类",
      "frontmatter": {},
      "regularPath": "/file/sort.html",
      "relativePath": "file/sort.md",
      "key": "v-192539be",
      "path": "/file/sort.html",
      "headers": [
        {
          "level": 2,
          "title": "冒泡排序",
          "slug": "冒泡排序"
        },
        {
          "level": 3,
          "title": "算法思想",
          "slug": "算法思想"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "快速排序",
          "slug": "快速排序"
        },
        {
          "level": 3,
          "title": "算法思想",
          "slug": "算法思想-2"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码-2"
        },
        {
          "level": 2,
          "title": "选择排序",
          "slug": "选择排序"
        },
        {
          "level": 3,
          "title": "算法思想",
          "slug": "算法思想-3"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码-3"
        },
        {
          "level": 2,
          "title": "插入排序",
          "slug": "插入排序"
        },
        {
          "level": 3,
          "title": "算法思想",
          "slug": "算法思想-4"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码-4"
        },
        {
          "level": 2,
          "title": "归并排序",
          "slug": "归并排序"
        },
        {
          "level": 3,
          "title": "算法思想",
          "slug": "算法思想-5"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码-5"
        },
        {
          "level": 2,
          "title": "复杂度及稳定性",
          "slug": "复杂度及稳定性"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/file/listBasics.html",
      "relativePath": "file/listBasics.md",
      "key": "v-70f3311e",
      "path": "/file/listBasics.html"
    }
  ],
  "themeConfig": {
    "sidebar": {
      "sidebarDepth": 3,
      "/file/": [
        {
          "title": "算法性能分析",
          "path": "/file/",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            [
              "",
              "快速了解"
            ],
            [
              "algorithmPerformance",
              "复杂度分析"
            ],
            [
              "memoryManagement",
              "内存管理"
            ]
          ],
          "initialOpenGroupIndex": 0
        },
        {
          "title": "排序",
          "path": "/file",
          "children": [
            "sort"
          ]
        },
        {
          "title": "搜索",
          "path": "/file",
          "children": [
            "search"
          ]
        },
        {
          "title": "数组",
          "path": "/file/",
          "sidebarDepth": 2,
          "children": [
            [
              "arrayBasics",
              "数组基础知识"
            ],
            [
              "array",
              "数组经典算法题"
            ]
          ],
          "initialOpenGroupIndex": 0
        },
        {
          "title": "链表",
          "path": "/file/",
          "sidebarDepth": 2,
          "children": [
            [
              "listBasics",
              "链表基础知识"
            ],
            [
              "list",
              "链表经典算法题"
            ]
          ],
          "initialOpenGroupIndex": 0
        },
        {
          "title": "leetcode算法题",
          "path": "/file/",
          "sidebarDepth": 2,
          "children": [
            [
              "leetcode",
              "每日一练"
            ]
          ],
          "initialOpenGroupIndex": 0
        },
        {
          "title": "算法拓展学习",
          "path": "/file/",
          "sidebarDepth": 2,
          "children": [
            [
              "expandAlgorithm",
              "拓展算法学习"
            ]
          ],
          "initialOpenGroupIndex": 0
        },
        {
          "title": "双指针算法题",
          "path": "/file/",
          "sidebarDepth": 2,
          "children": [
            "doublePointer"
          ],
          "initialOpenGroupIndex": 0
        }
      ],
      "/": [
        ""
      ]
    }
  }
}